receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
processors:
  batch: {}
  filter/health:
    error_mode: ignore
    traces:
      span:
        - 'attributes["http.target"] == "/healthz"'
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: basic
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/health, batch]
      exporters: [otlp/jaeger, debug]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
