#!/usr/bin/env python3
"""Build the cross-page search index for the docs site (S25).

The pages under `docs/site/` are self-contained and work from `file://`, so a
search bar cannot `fetch()` its neighbours (browsers block that on `file://`).
Instead this walks the pages at *commit* time, splits each into its `<section>`s,
and writes a small `docs/site/search-index.js` that every page loads with a plain
`<script>` — which does work offline.

It is generated, so it can go stale. `scripts/check-docs-pages.py` rebuilds it in
memory and fails if the committed file differs, which is what keeps it honest.

Usage:
    python3 scripts/search_index.py            # write docs/site/search-index.js
    python3 scripts/search_index.py --check     # exit 1 if it is stale
"""
from __future__ import annotations

import html as htmlmod
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "docs" / "site"
OUT = SITE / "search-index.js"

#: Cap the body text kept per section; a hit needs a snippet, not the whole page.
MAX_CHARS = 3000

SCRIPT_STYLE_RE = re.compile(r"<(script|style)\b[^>]*>.*?</\1>", re.S | re.I)
TAG_RE = re.compile(r"<[^>]+>")
SECTION_RE = re.compile(r'<section\b[^>]*\bid="([^"]+)"[^>]*>(.*?)</section>', re.S | re.I)
HEAD_RE = re.compile(r"<h[1-3]\b[^>]*>(.*?)</h[1-3]>", re.S | re.I)
TITLE_RE = re.compile(r"<title\b[^>]*>(.*?)</title>", re.S | re.I)


def _text(fragment: str) -> str:
    """Tags, scripts and entities out; whitespace collapsed."""
    fragment = SCRIPT_STYLE_RE.sub(" ", fragment)
    fragment = TAG_RE.sub(" ", fragment)
    return re.sub(r"\s+", " ", htmlmod.unescape(fragment)).strip()


def _heading(fragment: str) -> str:
    """The section's own heading, minus a leading `qnum` like `07`."""
    match = HEAD_RE.search(fragment)
    text = _text(match.group(1)) if match else ""
    return re.sub(r"^\d+\s*", "", text).strip()


def records() -> list[dict]:
    """One record per section: page, anchor, title, text."""
    out: list[dict] = []
    for page in sorted(SITE.glob("*.html")):
        doc = page.read_text(encoding="utf-8")
        for anchor, body in SECTION_RE.findall(doc):
            text = _text(body)
            if not text:
                continue
            out.append(
                {"p": page.name, "a": anchor, "t": _heading(body), "x": text[:MAX_CHARS]}
            )
    return out


def build() -> str:
    """The full contents of `search-index.js`."""
    data = json.dumps(records(), ensure_ascii=False, separators=(",", ":"))
    # A `</` inside a JS string is harmless in an external file, but escaping it
    # keeps the file safe if it is ever inlined into a <script> block.
    data = data.replace("</", "<\\/")
    return (
        "// Generated by scripts/search_index.py — do not edit by hand.\n"
        "// Rebuild: python3 scripts/search_index.py\n"
        f"window.__DOCS_SEARCH = {data};\n"
    )


def main() -> int:
    expected = build()
    if "--check" in sys.argv:
        actual = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if actual != expected:
            print(
                f"{OUT.relative_to(ROOT)} is stale — run: python3 scripts/search_index.py",
                file=sys.stderr,
            )
            return 1
        print(f"search index up to date ({len(records())} sections)")
        return 0
    OUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(records())} sections, {len(expected)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
