#!/bin/bash
# =============================================================================
# setup.sh — kind cluster -> SPIRE -> Keycloak -> OPA -> API/tools/agent,
# with a verification gate after each identity-critical step.
# Usage: ./scripts/setup.sh        (teardown: ./scripts/teardown.sh)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

say()  { printf "\n\033[1;34m== %s\033[0m\n" "$*"; }
ok()   { printf "\033[1;32m   ✓ %s\033[0m\n" "$*"; }
info() { printf "\033[2m   · %s\033[0m\n" "$*"; }
die()  { printf "\033[1;31m   ✗ %s\033[0m\n" "$*" >&2; exit 1; }

NS=agent-platform
SPIFFE_ID="spiffe://acme.com/ns/agent-platform/sa/agent"
MANIFESTS=deploy/kind/manifests

# ---------------------------------------------------------------------------
# Secrets are never committed. `.env` is gitignored and generated on first run;
# the Keycloak realm is rendered from it. Production: an External Secrets
# Operator syncs a manager (Vault / AWS Secrets Manager) into these same
# Kubernetes Secrets — see docs/secrets.md.
# ---------------------------------------------------------------------------
ENV_FILE=.env

gen_secret() { python3 -c "import secrets; print(secrets.token_hex(16))"; }

REQUIRED_SECRETS="DEMO_CLI_SECRET MANAGER_CLI_SECRET MCP_TOOLS_SECRET PORTAL_SECRET ADMIN_CLIENT_SECRET POSTGRES_PASSWORD"

ensure_secrets() {
  if [ ! -f "$ENV_FILE" ]; then
    info "generating $ENV_FILE with random demo secrets (gitignored)"
    umask 077
    cat > "$ENV_FILE" <<EOF
# Local secrets — GITIGNORED. Generated by scripts/setup.sh; never commit.
DEMO_CLI_SECRET=$(gen_secret)
MANAGER_CLI_SECRET=$(gen_secret)
MCP_TOOLS_SECRET=$(gen_secret)
# The web app's client (login) and the API's least-privilege admin client.
PORTAL_SECRET=$(gen_secret)
ADMIN_CLIENT_SECRET=$(gen_secret)
# Postgres (durable approvals + agent run checkpoints).
POSTGRES_PASSWORD=$(gen_secret)
# For a hosted LLM provider, uncomment and set (used only by the gateway):
# LLM_API_KEY=sk-...
EOF
  fi
  # Add any newly-required secret to an existing file (so an upgrade from an
  # older .env does not fail).
  local added=0
  for v in $REQUIRED_SECRETS; do
    if ! grep -q "^${v}=" "$ENV_FILE"; then
      printf '%s=%s\n' "$v" "$(gen_secret)" >> "$ENV_FILE"
      added=1
    fi
  done
  [ "$added" = "1" ] && info "added newly-required secrets to $ENV_FILE"
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
  for v in $REQUIRED_SECRETS; do
    [ -n "${!v:-}" ] || die "$v is missing from $ENV_FILE"
  done
}

say "0. prerequisites"
for bin in kind kubectl docker; do
  command -v "$bin" >/dev/null || die "$bin not found (kind: brew install kind)"
done
docker info >/dev/null 2>&1 || die "docker daemon not running"
ok "kind, kubectl, docker present"

say "1. kind cluster"
kind get clusters 2>/dev/null | grep -qx agent-platform || \
  kind create cluster --config deploy/kind/cluster.yaml
kubectl cluster-info --context kind-agent-platform >/dev/null
ok "cluster agent-platform"

say "2. build + load images"
# SPIRE server + agent are custom builds (jti plugin; no JWT-SVID cache) —
# see docker/spire-*.Dockerfile and spire-plugin/.
docker build -q -f docker/spire-server.Dockerfile -t agent-platform/spire-server-jti:demo . >/dev/null
docker build -q -f docker/spire-agent.Dockerfile  -t agent-platform/spire-agent-nocache:demo . >/dev/null
ok "spire-server-jti, spire-agent-nocache"
for svc in api tools agent gateway sandbox; do
  docker build -q -f "docker/$svc.Dockerfile" -t "agent-platform/$svc:demo" . >/dev/null
  kind load docker-image "agent-platform/$svc:demo" --name agent-platform >/dev/null
  ok "agent-platform/$svc:demo"
done
kind load docker-image agent-platform/spire-server-jti:demo --name agent-platform >/dev/null
kind load docker-image agent-platform/spire-agent-nocache:demo --name agent-platform >/dev/null

say "3. namespace + SPIRE"
kubectl apply -f "$MANIFESTS/namespace.yaml" >/dev/null

# Service mesh: Linkerd gives mTLS on *every* in-cluster hop. The app layer does
# SPIFFE mTLS on agent<->gateway; the mesh covers the rest (api/tools/agent,
# Keycloak, OPA, the observability stack) without changing the services.
# Optional: without the CLI the platform still runs, just in plaintext.
if command -v linkerd >/dev/null 2>&1; then
  if ! kubectl get ns linkerd >/dev/null 2>&1; then
    kubectl apply --server-side -f \
      "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml" >/dev/null
    linkerd install --crds 2>/dev/null | kubectl apply -f - >/dev/null
    linkerd install 2>/dev/null | kubectl apply -f - >/dev/null
  fi
  # The viz extension backs `tls-check.sh` (linkerd viz edges).
  if ! kubectl get ns linkerd-viz >/dev/null 2>&1; then
    linkerd viz install 2>/dev/null | kubectl apply -f - >/dev/null
  fi
  kubectl -n linkerd rollout status deploy/linkerd-destination --timeout=240s >/dev/null
  kubectl -n linkerd-viz rollout status deploy/web --timeout=240s >/dev/null
  kubectl annotate namespace $NS linkerd.io/inject=enabled --overwrite >/dev/null
  ok "linkerd up; $NS is mesh-injected (mTLS on every hop)"
else
  info "linkerd CLI not found — skipping the mesh (brew install linkerd); in-cluster traffic stays plaintext"
fi

kubectl apply -f "$MANIFESTS/spire/" >/dev/null
kubectl -n $NS rollout status statefulset/spire-server --timeout=240s >/dev/null
kubectl -n $NS rollout restart daemonset/spire-agent >/dev/null
kubectl -n $NS rollout status daemonset/spire-agent --timeout=180s >/dev/null
ok "spire-server + spire-agent ready"

SOCKET=/run/spire/server/private/api.sock
SPIRE="kubectl -n $NS exec spire-server-0 -- /opt/spire/bin/spire-server"

# Wait for at least one SPIRE agent to attest before registering workloads.
for _ in $(seq 1 12); do
  # `|| true` so a transient failure retries instead of tripping `set -e`.
  $SPIRE agent list -socketPath "$SOCKET" 2>/dev/null | grep -q 'SPIFFE ID' && break
  sleep 5
done
$SPIRE agent list -socketPath "$SOCKET" 2>/dev/null | grep -q 'SPIFFE ID' \
  || die "no attested SPIRE agent found"

# One registration entry per workload identity, **per attested agent**. With more
# than one node each runs its own SPIRE agent, and a workload is attested by the
# agent on its own node — a single entry parented to one agent leaves pods on
# every other node with "no identity issued". The gateway has its own SPIFFE ID
# so the agent can verify it over mTLS (and vice versa).
ensure_entry() { # ensure_entry <service-account> <spiffe-id>
  local sa="$1" id="$2" entry parent
  # Drop any existing entries for this identity (e.g. parented to a node that is
  # gone), then register one per attested agent.
  for entry in $($SPIRE entry show -socketPath "$SOCKET" -spiffeID "$id" 2>/dev/null \
    | awk '/Entry ID/{print $NF}'); do
    $SPIRE entry delete -socketPath "$SOCKET" -entryID "$entry" >/dev/null
  done
  for parent in $($SPIRE agent list -socketPath "$SOCKET" 2>/dev/null \
    | awk '/SPIFFE ID/{print $NF}'); do
    $SPIRE entry create -socketPath "$SOCKET" \
      -spiffeID "$id" -parentID "$parent" \
      -selector "k8s:ns:$NS" -selector "k8s:sa:$sa" >/dev/null
  done
  ok "registration entry: $id (k8s:sa=$sa)"
}

ensure_entry agent "$SPIFFE_ID"
ensure_entry gateway "spiffe://acme.com/ns/agent-platform/sa/gateway"

say "4. secrets + Keycloak"
ensure_secrets
RENDERED=$(mktemp)
python3 scripts/render.py "$MANIFESTS/keycloak/realm.json.tmpl" > "$RENDERED"
kubectl -n $NS create configmap keycloak-realm \
  --from-file=realm.json="$RENDERED" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
rm -f "$RENDERED"
ok "realm rendered from $ENV_FILE (client secrets are not in git)"
# The API needs the portal client secret (login) and the admin client secret
# (enrollment + role management), both least-privilege, plus the demo client
# secrets used by the scripted demo.
kubectl -n $NS create secret generic platform-secrets \
  --from-literal=DEMO_CLI_SECRET="$DEMO_CLI_SECRET" \
  --from-literal=MANAGER_CLI_SECRET="$MANAGER_CLI_SECRET" \
  --from-literal=PORTAL_SECRET="$PORTAL_SECRET" \
  --from-literal=ADMIN_CLIENT_SECRET="$ADMIN_CLIENT_SECRET" \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
# Recreate Keycloak so the realm is imported fresh. Its H2 database is
# ephemeral and the import strategy is IGNORE_EXISTING, so an existing realm
# would otherwise keep the previous client secrets.
kubectl -n $NS delete deploy keycloak --ignore-not-found --wait=true >/dev/null 2>&1
kubectl apply -f "$MANIFESTS/keycloak/keycloak.yaml" >/dev/null
kubectl -n $NS rollout status deploy/keycloak --timeout=300s >/dev/null
ok "keycloak ready (realm agent-platform imported)"

say "5. postgres (durable approvals + run state)"
kubectl -n $NS create secret generic postgres \
  --from-literal=password="$POSTGRES_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/data/" >/dev/null
kubectl -n $NS rollout status deploy/postgres --timeout=180s >/dev/null
ok "postgres ready (services pick it up via DATABASE_URL)"

say "6. OPA"
# Build the versioned bundle (revision stamped into every decision) and mount it.
POLICY_REVISION=$(./scripts/build-bundle.sh)
kubectl -n $NS create configmap opa-bundle \
  --from-file=authz.rego=dist/bundle/authz.rego \
  --from-file=data.json=dist/bundle/data.json \
  --from-file=.manifest=dist/bundle/.manifest \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/opa/" >/dev/null
# Restart OPA: the bundle files are mounted with subPath (which does not update
# in place) and OPA loads the bundle at startup, so a new revision needs a restart.
kubectl -n $NS rollout restart deploy/opa >/dev/null
kubectl -n $NS rollout status deploy/opa --timeout=120s >/dev/null
ok "opa serving policy bundle revision $POLICY_REVISION"

say "7. observability"
kubectl apply -f "$MANIFESTS/observability/" >/dev/null
kubectl -n $NS rollout status deploy/otel-collector --timeout=180s >/dev/null
kubectl -n $NS rollout status deploy/jaeger --timeout=180s >/dev/null
kubectl -n $NS rollout status deploy/prometheus --timeout=180s >/dev/null
kubectl -n $NS rollout status deploy/grafana --timeout=180s >/dev/null
ok "otel-collector, jaeger, prometheus + grafana ready (traces, metrics, dashboard)"

say "8. platform services"
# The optional provider key: only the gateway consumes it.
if [ -n "${LLM_API_KEY:-}" ]; then
  kubectl -n $NS create secret generic llm-api-key \
    --from-literal=LLM_API_KEY="$LLM_API_KEY" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  ok "llm-api-key secret created (consumed only by the gateway)"
fi
kubectl apply -f "$MANIFESTS/apps/" >/dev/null
kubectl -n $NS rollout restart deploy/api deploy/tools deploy/agent deploy/gateway deploy/sandbox >/dev/null
kubectl -n $NS rollout status deploy/api deploy/tools deploy/agent deploy/gateway deploy/sandbox \
  --timeout=240s >/dev/null
ok "api, tools, agent, gateway, sandbox ready"

say "9. autoscaling"
# metrics-server serves the metrics API over TLS. Give it a serving cert the API
# server can verify (rather than skipping verification), signed by a small CA we
# generate here.
TLS=$(mktemp -d)
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -subj "/CN=metrics-server-ca" \
  -keyout "$TLS/ca.key" -out "$TLS/ca.crt" 2>/dev/null
openssl req -newkey rsa:2048 -nodes -subj "/CN=metrics-server.kube-system.svc" \
  -keyout "$TLS/tls.key" -out "$TLS/tls.csr" 2>/dev/null
openssl x509 -req -in "$TLS/tls.csr" -CA "$TLS/ca.crt" -CAkey "$TLS/ca.key" -CAcreateserial \
  -days 3650 -out "$TLS/tls.crt" \
  -extfile <(printf "subjectAltName=DNS:metrics-server.kube-system.svc,DNS:metrics-server.kube-system.svc.cluster.local") 2>/dev/null
kubectl -n kube-system create secret tls metrics-server-tls \
  --cert="$TLS/tls.crt" --key="$TLS/tls.key" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/autoscaling/metrics-server.yaml" >/dev/null
# Pin the APIService to the generated CA (never skip TLS verification).
kubectl patch apiservice v1beta1.metrics.k8s.io --type=merge \
  -p "{\"spec\":{\"insecureSkipTLSVerify\":false,\"caBundle\":\"$(openssl base64 -A -in "$TLS/ca.crt")\"}}" >/dev/null
rm -rf "$TLS"
kubectl -n kube-system rollout status deploy/metrics-server --timeout=180s >/dev/null
kubectl apply -f "$MANIFESTS/autoscaling/hpa.yaml" >/dev/null
ok "metrics-server + HPAs ready (api/tools/agent/gateway/opa scale on CPU)"

say "10. GATE: the agent pod can fetch its SVID (no secrets involved)"
OUT=""
for _ in $(seq 1 12); do
  OUT=$(kubectl -n $NS exec deploy/agent -- python -c "
from agentnhi.identity import fetch_jwt_svid
print(fetch_jwt_svid('unix:///run/spire/sockets/agent.sock', 'smoke-test'))" 2>/dev/null) || OUT=""
  [ -n "$OUT" ] && break
  sleep 5
done
[ -n "$OUT" ] || die "agent could not fetch its SVID"
ok "agent holds a JWT-SVID issued to $SPIFFE_ID"

say "SETUP COMPLETE"
echo "Next: ./scripts/demo.sh        # the happy path + approval flow"
echo "      ./scripts/attack-tests.sh # watch the attacks fail"
