#!/bin/bash
# =============================================================================
# setup.sh — kind cluster -> Postgres -> SPIRE -> Keycloak -> OPA -> API/tools/agent,
# with a verification gate after each identity-critical step.
# Usage: ./scripts/setup.sh        (teardown: ./scripts/teardown.sh)
# =============================================================================
set -euo pipefail
# shellcheck source=lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
cd "$(dirname "$0")/.."

say()  { printf "\n\033[1;34m== %s\033[0m\n" "$*"; }
ok()   { printf "\033[1;32m   ✓ %s\033[0m\n" "$*"; }
info() { printf "\033[2m   · %s\033[0m\n" "$*"; }
die()  { printf "\033[1;31m   ✗ %s\033[0m\n" "$*" >&2; exit 1; }

NS=agent-platform
SPIFFE_ID="spiffe://acme.com/ns/agent-platform/sa/agent"
MANIFESTS=deploy/kind/manifests

# ---------------------------------------------------------------------------
# Secrets are never committed. `.env` is gitignored and generated on first run;
# the Keycloak realm is rendered from it. Production: an External Secrets
# Operator syncs a manager (Vault / AWS Secrets Manager) into these same
# Kubernetes Secrets — see docs/secrets.md.
# ---------------------------------------------------------------------------
ENV_FILE=.env

gen_secret() { python3 -c "import secrets; print(secrets.token_hex(16))"; }

REQUIRED_SECRETS="DEMO_CLI_SECRET MANAGER_CLI_SECRET MCP_TOOLS_SECRET PORTAL_SECRET ADMIN_CLIENT_SECRET POSTGRES_PASSWORD SPIRE_DB_PASSWORD KEYCLOAK_DB_PASSWORD"

ensure_secrets() {
  if [ ! -f "$ENV_FILE" ]; then
    info "generating $ENV_FILE with random demo secrets (gitignored)"
    umask 077
    cat > "$ENV_FILE" <<EOF
# Local secrets — GITIGNORED. Generated by scripts/setup.sh; never commit.
DEMO_CLI_SECRET=$(gen_secret)
MANAGER_CLI_SECRET=$(gen_secret)
MCP_TOOLS_SECRET=$(gen_secret)
# The web app's client (login) and the API's least-privilege admin client.
PORTAL_SECRET=$(gen_secret)
ADMIN_CLIENT_SECRET=$(gen_secret)
# Postgres (durable approvals + agent run checkpoints).
POSTGRES_PASSWORD=$(gen_secret)
# SPIRE's registration registry (S1) — its own least-privilege role, in the same
# Postgres, so the identity root of trust no longer lives in a file beside the
# server.
SPIRE_DB_PASSWORD=$(gen_secret)
# Keycloak's realms and users (S2) — its own least-privilege role in the same
# Postgres, so accounts survive a restart and two replicas can share them.
KEYCLOAK_DB_PASSWORD=$(gen_secret)
# For a hosted LLM provider, uncomment and set (used only by the gateway):
# LLM_API_KEY=sk-...
EOF
  fi
  # Add any newly-required secret to an existing file (so an upgrade from an
  # older .env does not fail).
  local added=0
  for v in $REQUIRED_SECRETS; do
    if ! grep -q "^${v}=" "$ENV_FILE"; then
      printf '%s=%s\n' "$v" "$(gen_secret)" >> "$ENV_FILE"
      added=1
    fi
  done
  [ "$added" = "1" ] && info "added newly-required secrets to $ENV_FILE"
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
  for v in $REQUIRED_SECRETS; do
    [ -n "${!v:-}" ] || die "$v is missing from $ENV_FILE"
  done
}

say "0. prerequisites"
for bin in kind kubectl docker; do
  command -v "$bin" >/dev/null || die "$bin not found (kind: brew install kind)"
done
docker info >/dev/null 2>&1 || die "docker daemon not running"
ok "kind, kubectl, docker present"

say "1. kind cluster"
kind get clusters 2>/dev/null | grep -qx agent-platform || \
  kind create cluster --config deploy/kind/cluster.yaml
# Pin, then say which cluster we are on. Set KUBE_CONTEXT to target another one.
kubectl cluster-info >/dev/null 2>&1 \
  || die "cannot reach context $KUBE_CONTEXT — is that cluster running?"
ok "cluster $KUBE_CONTEXT"

say "2. build + load images"
# SPIRE server + agent are custom builds (jti plugin; no JWT-SVID cache) —
# see docker/spire-*.Dockerfile and spire-plugin/.
docker build -q -f docker/spire-server.Dockerfile -t agent-platform/spire-server-jti:demo . >/dev/null
docker build -q -f docker/spire-agent.Dockerfile  -t agent-platform/spire-agent-nocache:demo . >/dev/null
ok "spire-server-jti, spire-agent-nocache"
# Stamp each image with the revision it was built from (scripts/check-images.sh).
# A dirty tree is marked, because "the image matches HEAD" would be a lie.
GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
git diff --quiet 2>/dev/null || GIT_SHA="$GIT_SHA-dirty"
for svc in api tools agent gateway sandbox keycloak; do
  docker build -q --build-arg "GIT_SHA=$GIT_SHA" \
    -f "docker/$svc.Dockerfile" -t "agent-platform/$svc:demo" . >/dev/null
  kind load docker-image "agent-platform/$svc:demo" --name agent-platform >/dev/null
  ok "agent-platform/$svc:demo"
done
kind load docker-image agent-platform/spire-server-jti:demo --name agent-platform >/dev/null
kind load docker-image agent-platform/spire-agent-nocache:demo --name agent-platform >/dev/null

say "3. namespace + mesh + secrets"
kubectl apply -f "$MANIFESTS/namespace.yaml" >/dev/null

# Service mesh: Linkerd gives mTLS on *every* in-cluster hop. The app layer does
# SPIFFE mTLS on agent<->gateway; the mesh covers the rest (api/tools/agent,
# Keycloak, OPA, the observability stack) without changing the services.
# Optional: without the CLI the platform still runs, just in plaintext.
if command -v linkerd >/dev/null 2>&1; then
  if ! kubectl get ns linkerd >/dev/null 2>&1; then
    kubectl apply --server-side -f \
      "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml" >/dev/null
    linkerd install --crds 2>/dev/null | kubectl apply -f - >/dev/null
    linkerd install 2>/dev/null | kubectl apply -f - >/dev/null
  fi
  # The viz extension backs `tls-check.sh` (linkerd viz edges).
  if ! kubectl get ns linkerd-viz >/dev/null 2>&1; then
    linkerd viz install 2>/dev/null | kubectl apply -f - >/dev/null
  fi
  kubectl -n linkerd rollout status deploy/linkerd-destination --timeout=240s >/dev/null
  kubectl -n linkerd-viz rollout status deploy/web --timeout=240s >/dev/null
  kubectl annotate namespace $NS linkerd.io/inject=enabled --overwrite >/dev/null
  ok "linkerd up; $NS is mesh-injected (mTLS on every hop)"
else
  info "linkerd CLI not found — skipping the mesh (brew install linkerd); in-cluster traffic stays plaintext"
fi

# Secrets are generated into a gitignored .env on first run and loaded here, so
# both the Postgres password and SPIRE's datastore password exist before either
# is applied. Keycloak's realm is rendered from the same file, in step 6.
ensure_secrets
ok "$ENV_FILE present; required secrets loaded"

# ---------------------------------------------------------------------------
# Postgres comes before SPIRE because SPIRE's registration registry now lives in
# it (S1). That inverts the demo's critical path — identity needs the database —
# which is exactly why production points this at a managed, HA database.
# ---------------------------------------------------------------------------
say "4. postgres (durable state; SPIRE's registry lives here too)"
kubectl -n $NS create secret generic postgres \
  --from-literal=password="$POSTGRES_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/data/" >/dev/null
kubectl -n $NS rollout status deploy/postgres --timeout=180s >/dev/null
# One least-privilege role and database per consumer, so nothing shares the
# application's credentials. `CREATE DATABASE` cannot run inside a transaction
# block, so it is guarded with a query rather than wrapped in a DO block. Each
# role's password is re-set every run so it always matches .env.
PSQL="kubectl -n $NS exec deploy/postgres -- psql -U agent -d"
ensure_database() { # ensure_database <name> <password>
  local name="$1" password="$2"
  $PSQL postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$name'" 2>/dev/null | grep -q 1 \
    || $PSQL postgres -c "CREATE ROLE $name LOGIN PASSWORD '$password'" >/dev/null
  $PSQL postgres -c "ALTER ROLE $name LOGIN PASSWORD '$password'" >/dev/null
  $PSQL postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$name'" 2>/dev/null | grep -q 1 \
    || $PSQL postgres -c "CREATE DATABASE $name OWNER $name" >/dev/null
}
ensure_database spire "$SPIRE_DB_PASSWORD"
ensure_database keycloak "$KEYCLOAK_DB_PASSWORD"
ok "postgres ready; databases 'spire' and 'keycloak' ready"

say "5. SPIRE"
# The server config carries the datastore password, so it is rendered from a
# template into a Secret — never committed. Same pattern as the Keycloak realm.
SPIRE_CONF=$(mktemp)
python3 scripts/render.py "$MANIFESTS/spire/server.conf.tmpl" > "$SPIRE_CONF"
kubectl -n $NS create secret generic spire-server-config \
  --from-file=server.conf="$SPIRE_CONF" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
rm -f "$SPIRE_CONF"
ok "server.conf rendered from server.conf.tmpl (the datastore password is a Secret)"

# The trust-bundle ConfigMap changed owner (Notifier -> BundlePublisher, S11).
# A leftover field manager still owns .data.bundle.crt, and Server-Side Apply
# refuses to take over a field another manager owns — the publish then fails
# every tick with "Apply failed with 1 conflict" and the agents stay on a stale
# CA. Recreate the (empty) placeholder so the publisher owns it outright; it
# republishes within ~30s. A no-op on a fresh cluster.
kubectl -n $NS delete configmap spire-bundle --ignore-not-found >/dev/null 2>&1 || true
kubectl apply -f "$MANIFESTS/spire/" >/dev/null
# Restart the server too, not just the agents. Its config comes from a Secret
# and its image from a reused `:demo` tag, so a re-run would otherwise keep
# running the previous SPIRE with the previous config — the same trap
# check-images.sh warns about, and why OPA is restarted in step 7. Expect ~30s
# before the fresh server republishes the trust bundle (the bundle publisher's
# tick); the agents retry until it lands.
kubectl -n $NS rollout restart statefulset/spire-server >/dev/null
kubectl -n $NS rollout status statefulset/spire-server --timeout=240s >/dev/null
kubectl -n $NS rollout restart daemonset/spire-agent >/dev/null
kubectl -n $NS rollout status daemonset/spire-agent --timeout=300s >/dev/null
ok "spire-server + spire-agent ready"

SOCKET=/run/spire/server/private/api.sock
SPIRE="kubectl -n $NS exec spire-server-0 -- /opt/spire/bin/spire-server"

# Wait until every running SPIRE agent has attested. They attest a moment apart,
# and an agent that attests *after* we register gets no entries — leaving its
# node's workloads with "no identity issued".
want=$(kubectl -n $NS get pods -l app=spire-agent --field-selector=status.phase=Running \
  --no-headers 2>/dev/null | wc -l | tr -d ' ')
for _ in $(seq 1 24); do
  # `|| true` so a transient failure retries instead of tripping `set -e`.
  have=$($SPIRE agent list -socketPath "$SOCKET" 2>/dev/null | grep -c 'SPIFFE ID' || true)
  [ "${have:-0}" -ge "${want:-1}" ] && [ "${have:-0}" -gt 0 ] && break
  sleep 5
done
$SPIRE agent list -socketPath "$SOCKET" 2>/dev/null | grep -q 'SPIFFE ID' \
  || die "no attested SPIRE agent found"

# One registration entry per workload identity, **per attested agent**. With more
# than one node each runs its own SPIRE agent, and a workload is attested by the
# agent on its own node — a single entry parented to one agent leaves pods on
# every other node with "no identity issued". The gateway has its own SPIFFE ID
# so the agent can verify it over mTLS (and vice versa).
ensure_entry() { # ensure_entry <service-account> <spiffe-id>
  local sa="$1" id="$2" entry parent
  # Drop any existing entries for this identity (e.g. parented to a node that is
  # gone), then register one per attested agent.
  for entry in $($SPIRE entry show -socketPath "$SOCKET" -spiffeID "$id" 2>/dev/null \
    | awk '/Entry ID/{print $NF}'); do
    $SPIRE entry delete -socketPath "$SOCKET" -entryID "$entry" >/dev/null
  done
  for parent in $($SPIRE agent list -socketPath "$SOCKET" 2>/dev/null \
    | awk '/SPIFFE ID/{print $NF}'); do
    $SPIRE entry create -socketPath "$SOCKET" \
      -spiffeID "$id" -parentID "$parent" \
      -selector "k8s:ns:$NS" -selector "k8s:sa:$sa" >/dev/null
  done
  ok "registration entry: $id (k8s:sa=$sa)"
}

ensure_entry agent "$SPIFFE_ID"
ensure_entry gateway "spiffe://acme.com/ns/agent-platform/sa/gateway"
# api and tools carry SVIDs too (S7): they are called by the agent, and that hop
# is proved at the transport rather than trusted from the mesh.
ensure_entry api "spiffe://acme.com/ns/agent-platform/sa/api"
ensure_entry tools "spiffe://acme.com/ns/agent-platform/sa/tools"

say "6. Keycloak"
RENDERED=$(mktemp)
python3 scripts/render.py "$MANIFESTS/keycloak/realm.json.tmpl" > "$RENDERED"
kubectl -n $NS create configmap keycloak-realm \
  --from-file=realm.json="$RENDERED" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
rm -f "$RENDERED"
ok "realm rendered from $ENV_FILE (client secrets are not in git)"
# The API needs the portal client secret (login) and the admin client secret
# (enrollment + role management), both least-privilege, plus the demo client
# secrets used by the scripted demo.
kubectl -n $NS create secret generic platform-secrets \
  --from-literal=DEMO_CLI_SECRET="$DEMO_CLI_SECRET" \
  --from-literal=MANAGER_CLI_SECRET="$MANAGER_CLI_SECRET" \
  --from-literal=PORTAL_SECRET="$PORTAL_SECRET" \
  --from-literal=ADMIN_CLIENT_SECRET="$ADMIN_CLIENT_SECRET" \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl -n $NS create secret generic keycloak-db \
  --from-literal=password="$KEYCLOAK_DB_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/keycloak/keycloak-env.yaml" >/dev/null
# Import the realm *before* the server starts, so the two never contend for the
# database and the import is an explicit step rather than a side effect of
# startup. `--override=false` makes it a no-op once the realm exists, which is
# what keeps accounts enrolled at runtime across a re-run (S2) — the old flow had
# to delete Keycloak every run because its database was ephemeral.
kubectl -n $NS delete job keycloak-import --ignore-not-found --wait=true >/dev/null 2>&1
kubectl apply -f "$MANIFESTS/keycloak/keycloak-import.yaml" >/dev/null
kubectl -n $NS wait --for=condition=complete job/keycloak-import --timeout=300s >/dev/null
kubectl apply -f "$MANIFESTS/keycloak/keycloak.yaml" >/dev/null
# Restart it as well, not just apply it. The image tag is reused and the config
# arrives as a mounted ConfigMap, so `apply` alone leaves the previous build (and
# the previous env) running — exactly the trap check-images.sh exists to catch,
# and why OPA and the app deployments are restarted too. Cheap now: the realm is
# in Postgres, so a restart imports nothing and logs nobody out permanently.
kubectl -n $NS rollout restart deploy/keycloak >/dev/null
kubectl -n $NS rollout status deploy/keycloak --timeout=420s >/dev/null
ok "keycloak ready (realm imported by job; 2 replicas; Postgres-backed)"

say "7. OPA"
# Build the versioned bundle (revision stamped into every decision) and mount it.
POLICY_REVISION=$(./scripts/build-bundle.sh)
kubectl -n $NS create configmap opa-bundle \
  --from-file=authz.rego=dist/bundle/authz.rego \
  --from-file=data.json=dist/bundle/data.json \
  --from-file=.manifest=dist/bundle/.manifest \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/opa/" >/dev/null
# Restart OPA: the bundle files are mounted with subPath (which does not update
# in place) and OPA loads the bundle at startup, so a new revision needs a restart.
kubectl -n $NS rollout restart deploy/opa >/dev/null
kubectl -n $NS rollout status deploy/opa --timeout=120s >/dev/null
ok "opa serving policy bundle revision $POLICY_REVISION"

say "8. observability"
kubectl apply -f "$MANIFESTS/observability/" >/dev/null
kubectl -n $NS rollout status deploy/otel-collector --timeout=180s >/dev/null
kubectl -n $NS rollout status deploy/jaeger --timeout=180s >/dev/null
kubectl -n $NS rollout status deploy/prometheus --timeout=180s >/dev/null
kubectl -n $NS rollout status deploy/grafana --timeout=180s >/dev/null
ok "otel-collector, jaeger, prometheus + grafana ready (traces, metrics, dashboard)"

say "9. platform services"
# The optional provider key: only the gateway consumes it.
if [ -n "${LLM_API_KEY:-}" ]; then
  kubectl -n $NS create secret generic llm-api-key \
    --from-literal=LLM_API_KEY="$LLM_API_KEY" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  ok "llm-api-key secret created (consumed only by the gateway)"
fi
kubectl apply -f "$MANIFESTS/apps/" >/dev/null
kubectl -n $NS rollout restart deploy/api deploy/tools deploy/agent deploy/gateway deploy/sandbox >/dev/null
kubectl -n $NS rollout status deploy/api deploy/tools deploy/agent deploy/gateway deploy/sandbox \
  --timeout=240s >/dev/null
ok "api, tools, agent, gateway, sandbox ready"

# ---------------------------------------------------------------------------
# The browser edge (S7b). Everything else here is workload-to-workload; this is
# the one hop a *person* uses, and it carried user tokens in the clear: the
# browser reached the API through `kubectl port-forward`, plaintext end to end.
# Now TLS terminates at an ingress, with a certificate we can verify.
# ---------------------------------------------------------------------------
say "10. browser edge (TLS at the ingress)"
EDGE=.edge # gitignored: the CA, its key and the certificate never enter git
# The upstream manifest is pinned by tag, and every image in it by digest.
if ! kubectl get ns ingress-nginx >/dev/null 2>&1; then
  kubectl apply -f \
    "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.15.1/deploy/static/provider/cloud/deploy.yaml" >/dev/null
  ok "ingress-nginx controller-v1.15.1 installed (namespace ingress-nginx)"
fi
kubectl -n ingress-nginx rollout status deploy/ingress-nginx-controller --timeout=240s >/dev/null
# The admission webhook has failurePolicy=Fail, so an Ingress created while the
# certgen jobs are still running is rejected — "no endpoints available". Wait for
# them before applying ours. (On a re-run they may be complete and garbage
# collected: `get` fails, so the wait is skipped rather than fatal.)
for j in ingress-nginx-admission-create ingress-nginx-admission-patch; do
  kubectl -n ingress-nginx get job "$j" >/dev/null 2>&1 \
    && kubectl -n ingress-nginx wait --for=condition=complete "job/$j" --timeout=180s >/dev/null \
    || true
done

# A certificate signed by a CA we generate, rather than a self-signed cert the
# client has to trust blindly: `curl --cacert $EDGE/ca.crt` (and a browser
# importing it) verifies the chain *and* the name on the certificate. Generated
# once and kept, so a browser does not have to re-import it every run.
#
# The extensions are not decoration. A CA without basicConstraints + keyUsage is
# accepted by curl and rejected by anything strict — Python/OpenSSL 3 refuses the
# chain outright ("CA cert does not include key usage extension"), which is the
# difference between a certificate that *verifies* and one that is merely
# present. The leaf names the host and expires inside the 398-day browser limit.
if [ ! -f "$EDGE/ca.crt" ]; then
  mkdir -p "$EDGE"; umask 077
  cat > "$EDGE/openssl.cnf" <<'EOF'
[ req ]
distinguished_name = dn
[ dn ]
[ v3_ca ]
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
[ v3_leaf ]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost, DNS:agent-platform.local
EOF
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -subj "/CN=agent-platform edge CA" \
    -config "$EDGE/openssl.cnf" -extensions v3_ca \
    -keyout "$EDGE/ca.key" -out "$EDGE/ca.crt" 2>/dev/null
  openssl req -new -newkey rsa:2048 -nodes -subj "/CN=localhost" \
    -config "$EDGE/openssl.cnf" -keyout "$EDGE/tls.key" -out "$EDGE/tls.csr" 2>/dev/null
  openssl x509 -req -in "$EDGE/tls.csr" -CA "$EDGE/ca.crt" -CAkey "$EDGE/ca.key" \
    -CAcreateserial -days 397 -out "$EDGE/tls.crt" \
    -extfile "$EDGE/openssl.cnf" -extensions v3_leaf 2>/dev/null
  rm -f "$EDGE/tls.csr" "$EDGE/ca.srl"
  ok "edge CA + certificate generated into $EDGE (gitignored)"
fi
kubectl -n $NS create secret tls agent-platform-tls \
  --cert="$EDGE/tls.crt" --key="$EDGE/tls.key" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/edge/" >/dev/null
ok "ingress agent-platform -> api:8080, tls secret agent-platform-tls"

# GATE: fetch /healthz through the edge from outside the cluster, the way a
# browser does — over https, with our CA, no -k. A certificate we skip
# verifying would prove nothing.
EDGE_PORT=9443
kubectl -n ingress-nginx port-forward svc/ingress-nginx-controller $EDGE_PORT:443 >/dev/null 2>&1 &
EDGE_PF=$!
trap 'kill $EDGE_PF 2>/dev/null || true' EXIT
EDGE_CODE=""
for _ in $(seq 1 20); do
  EDGE_CODE=$(curl -s -o /dev/null -w '%{http_code}' --cacert "$EDGE/ca.crt" \
    --resolve "localhost:$EDGE_PORT:127.0.0.1" "https://localhost:$EDGE_PORT/healthz" 2>/dev/null || true)
  [ "$EDGE_CODE" = "200" ] && break
  sleep 2
done
kill $EDGE_PF 2>/dev/null || true; trap - EXIT
[ "$EDGE_CODE" = "200" ] \
  || die "the edge did not answer over TLS with our CA (got '${EDGE_CODE:-nothing}')"
ok "https://localhost:8443/healthz answered 200 with a certificate that verifies"

say "11. autoscaling"
# metrics-server serves the metrics API over TLS. Give it a serving cert the API
# server can verify (rather than skipping verification), signed by a small CA we
# generate here.
TLS=$(mktemp -d)
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -subj "/CN=metrics-server-ca" \
  -keyout "$TLS/ca.key" -out "$TLS/ca.crt" 2>/dev/null
openssl req -newkey rsa:2048 -nodes -subj "/CN=metrics-server.kube-system.svc" \
  -keyout "$TLS/tls.key" -out "$TLS/tls.csr" 2>/dev/null
openssl x509 -req -in "$TLS/tls.csr" -CA "$TLS/ca.crt" -CAkey "$TLS/ca.key" -CAcreateserial \
  -days 3650 -out "$TLS/tls.crt" \
  -extfile <(printf "subjectAltName=DNS:metrics-server.kube-system.svc,DNS:metrics-server.kube-system.svc.cluster.local") 2>/dev/null
kubectl -n kube-system create secret tls metrics-server-tls \
  --cert="$TLS/tls.crt" --key="$TLS/tls.key" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f "$MANIFESTS/autoscaling/metrics-server.yaml" >/dev/null
# Pin the APIService to the generated CA (never skip TLS verification).
kubectl patch apiservice v1beta1.metrics.k8s.io --type=merge \
  -p "{\"spec\":{\"insecureSkipTLSVerify\":false,\"caBundle\":\"$(openssl base64 -A -in "$TLS/ca.crt")\"}}" >/dev/null
rm -rf "$TLS"
kubectl -n kube-system rollout status deploy/metrics-server --timeout=180s >/dev/null
kubectl apply -f "$MANIFESTS/autoscaling/hpa.yaml" >/dev/null
ok "metrics-server + HPAs ready (api/tools/agent/gateway/opa scale on CPU)"

say "12. GATE: the agent pod can fetch its SVID (no secrets involved)"
OUT=""
for _ in $(seq 1 12); do
  OUT=$(kubectl -n $NS exec deploy/agent -- python -c "
from agentnhi.identity import fetch_jwt_svid
print(fetch_jwt_svid('unix:///run/spire/sockets/agent.sock', 'smoke-test'))" 2>/dev/null) || OUT=""
  [ -n "$OUT" ] && break
  sleep 5
done
[ -n "$OUT" ] || die "agent could not fetch its SVID"
ok "agent holds a JWT-SVID issued to $SPIFFE_ID"

say "are the pods running what we just built?"
./scripts/check-images.sh

say "SETUP COMPLETE"
echo "Next: ./scripts/demo.sh        # the happy path + approval flow"
echo "      ./scripts/attack-tests.sh # watch the attacks fail"
