"""Shared test constants."""
ISSUER = "http://keycloak:8080/realms/agent-platform"
AUDIENCE = "mcp-tools"
AGENT = "spiffe://acme.com/ns/agent-platform/sa/agent"
OTHER_AGENT = "spiffe://acme.com/ns/agent-platform/sa/rogue"
